# Generated by Django 5.2.8 on 2026-05-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicrecord',
            name='semester_taken',
            field=models.IntegerField(default=1),
        ),
    ]
