# Generated by Django 6.0.5 on 2026-05-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_academicrecord_semester_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
